# Generated by Django 4.2.4 on 2023-08-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('interview_start_time', models.DateTimeField()),
                ('interview_end_time', models.DateTimeField()),
                ('hr_number', models.CharField(max_length=20)),
                ('hr_mail_id', models.EmailField(max_length=254)),
                ('hr_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('round', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('ToDo', 'ToDo'), ('Rescheduled', 'Rescheduled')], max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(choices=[('Python', 'Python'), ('Data Engineering', 'Data Engineering')], max_length=50)),
            ],
        ),
    ]
